config/routes.rb
Rails.application.routes.draw do
  resources :flats

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/models/search.rb
class Search < RailsSimpleSearch::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[ show edit update destroy ]

  # GET /flats or /flats.json
  def index
    @flats = Flat.all
  end

  # GET /flats/1 or /flats/1.json
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats or /flats.json
  def create
    @flat = Flat.new(flat_params)

    respond_to do |format|
      if @flat.save
        format.html { redirect_to flat_url(@flat), notice: "Flat was successfully created." }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flats/1 or /flats/1.json
  def update
    respond_to do |format|
      if @flat.update(flat_params)
        format.html { redirect_to flat_url(@flat), notice: "Flat was successfully updated." }
        format.json { render :show, status: :ok, location: @flat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @flat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flats/1 or /flats/1.json
  def destroy
    @flat.destroy

    respond_to do |format|
      format.html { redirect_to flats_url, notice: "Flat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flat_params
      params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  @search = Search.new(Flat, params[:search])
  @flats = @search.run.paginate(page: params[:page], per_page: 20).order('name')
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_flat.html.erb
<div id="<%= dom_id flat %>">
  <p><b>
    <%= flat.name %>
  </b></p>

  <p>
    <%= flat.address %>
  </p>

  <p>
    <%= flat.description %>
  </p>

  <p>
    <i class="fa-solid fa-sack-dollar"></i>
    <%= flat.price_per_night %>
  </p>

  <p>
    <i class="fa-solid fa-users-rectangle"></i>
    <%= flat.number_of_guests %>
  </p>

</div>

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<h1>Editing flat</h1>

<%= render "form", flat: @flat %>

<br>

<div>
  <%= link_to "Show this flat", @flat %> |
  <%= link_to "Back to flats", flats_path %>
</div>

app/views/flats/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h1>All our flats</h1>



<div id="flats" class="row">
  <% @flats.each do |flat| %>
  <div class="col-3">
    <div class="card" style="width: 18rem; padding: 1rem;">
        <%= render flat %>
        <p>
          <%= link_to "more info", flat %>
        </p>
    </div>
    <br>
  </div>
  <% end %>
</div>

         <h4 class="fa-solid fa-circle-plus" > <%= link_to "Make a new flat", new_flat_path %> </h4>

</div>

app/views/flats/new.html.erb
<h1>New flat</h1>

<%= render "form", flat: @flat %>

<br>

<div>
  <%= link_to "Back to flats", flats_path %>
</div>

app/views/flats/show.html.erb
<div class="container" >
  <p style="color: green"><%= notice %></p>

    <%= render @flat %>

    <div >

        <li class="fa-regular fa-pen-to-square">
      <%= link_to "Edit this flat", edit_flat_path(@flat) %> |
        </li>
          <br>
                <br>

        <li class="fa-solid fa-left-long">
      <%= link_to "Back to flats", flats_path %>
        </li>
          <br>
          
        <li class="btn btn-outline-danger">
      <%= button_to "Destroy this flat", @flat, method: :delete %>
        </li>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/search/search.html.erb
<% form_for @search, url => "/xxxxxx" do |f| %>

  <%=f.label :name %>
  <%=f.text_field :name %>

  <%=f.label "first name or last name" %>
  <%=f.text_field "first_name_or_last_name" %>

  <%=f.submit %>
<% end %>

<% @flats.each do |flat| %>
 <%= # show the attributes of user %>
<% end %>